autogit4unimoose.sh

sed -i 's/....'

autogit_global_a->global_conf
developer_mode_file->dev_mode_f
kigit_UNICORN_MOOSE_DEVELOPER_MODE_CONFIG->dev_mode_flag_f
main_script_file->main_script_f
github_token->github_api_token
homepageUrl_githubpages_standard->github_pages_repo_url
fetch_github_token->load_github_token_from_f
read_kigit_config->load_config_f_kigit
change_ownership->chown_local_f
setup_git->init_git_repo_local
ensure_branch->change_or_create_new_branch
handle_repository->create_repo
update_files->create_readmemd
sync_repo->push_sync_git_repository
create_html_page->create_html_page
update_kigit_txt->update_config_file_kigit
create_g_first_run->create_first_run_py

